# Generated by Django 2.0 on 2017-12-17 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('dateInit', models.DateField(auto_now=True)),
                ('nomApe', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=1)),
                ('dateNac', models.DateField()),
                ('address', models.CharField(max_length=200)),
                ('ocupation', models.CharField(max_length=100)),
                ('telCel', models.CharField(max_length=12)),
                ('alergies', models.CharField(max_length=150)),
                ('operations', models.CharField(max_length=150)),
                ('diabettes', models.BooleanField()),
                ('hipertension', models.BooleanField()),
                ('others', models.CharField(max_length=120)),
                ('treatMedics', models.CharField(max_length=120)),
                ('state', models.BooleanField(default=True)),
            ],
        ),
    ]
